version: '3.8'

services:
  dropwizard-app:
    build: .
    ports:
      - "8888:8888"
      - "8889:8889"
    depends_on:
      - kafka
      - zookeeper
      - pulsar
      - redis
    environment:
      KAFKA_SERVERS: kafka:9092
      ZK_CONNECTION_STRING: zookeeper:2181
      PULSAR_SERVICE_URL: pulsar://pulsar:6650
      REDIS_HOST: redis
      REDIS_PORT: 6379

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  pulsar:
    image: apachepulsar/pulsar:latest
    command: ["bin/pulsar", "standalone"]

  redis:
    image: redis:latest
