---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sockkeeper-config
data:
  config.yml: |
    logging:
      level: INFO
      loggers:
        sockkeeper: INFO

    server:
      applicationConnectors:
        - type: http
          port: 8888
      adminConnectors:
        - type: http
          port: 8889

    kafka:
      servers: host.docker.internal:9092

    zk:
      connectionString: host.docker.internal:2181
      connectionTimeout: 15000
      sessionTimeout: 1000
      retryBaseSleepTime: 10000
      maxRetry: 3

    pulsar:
      serviceUrl: pulsar://host.docker.internal:6650
      adminUrl: http://host.docker.internal:8080

    redis:
      host: host.docker.internal
      port: 6379
    
    sideline-topic: sockkeeper-sideline

---
apiVersion: v1
kind: Service
metadata:
  name: sockkeeper-service
spec:
  selector:
    app: sockkeeper
  ports:
    - name: http
      port: 80
      targetPort: 8888
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sk-node
spec:
  serviceName: sockkeeper-headless
  replicas: 3
  selector:
    matchLabels:
      app: sockkeeper
  template:
    metadata:
      labels:
        app: sockkeeper
    spec:
      containers:
        - name: sockkeeper
          image: sockkeeper
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
            - containerPort: 8889
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yml
              subPath: config.yml
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "2"
      volumes:
        - name: config-volume
          configMap:
            name: sockkeeper-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 50000
    
    defaults
      log global
      mode http
      option httplog
      option dontlognull
      timeout connect 100000ms
      timeout client 900000ms  # 15 min for regular HTTP
      timeout server 900000ms  # 15 min for regular HTTP
      timeout tunnel 86400000ms  # 24 hours for WebSocket tunnels
    
    frontend http_front
      bind *:80
      default_backend sockkeeper_back
    
    backend sockkeeper_back
      balance leastconn
      option http-server-close
      option forwardfor
      timeout tunnel 86400000ms  # WebSockets stay open for 24 hours
      timeout queue 900000ms
      timeout connect 100000ms
      server sockkeeper1 sockkeeper-service:80 check

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:latest
          command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: haproxy-config

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 8181   # Change from 80 to avoid conflicts
      targetPort: 80
  type: LoadBalancer
